version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/.env
    command: sh -c "/limiter"
    networks:
      - localNetwork

  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - localNetwork

volumes:
  cache:
    driver: local

networks:
  localNetwork:
    driver: bridge